@startuml  phone_sequence
autonumber 1

actor Caller as Caller order 1
participant Standard order 2
actor Correspondent order 3

Caller -> Standard: Entry phone booth
Caller -> Standard: Insert money
activate Standard
group delay 2min
Caller -> Standard : Compose number
Standard -> Correspondent : Start Call 
group times up 
Standard -> Caller : End call
deactivate Standard 
end
end
group Call
Correspondent -> Standard : Available 
activate Standard
Caller <-> Correspondent : Conversation 
Standard ->> Caller : Consume balance
Caller ->> Standard : Hang up
deactivate Standard
Correspondent ->> Standard : Hang up
deactivate Standard
group if busy
Standard ->> Caller : End call
end
end
Standard ->> Caller : Return balance

@enduml
